version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: abhishekkumargaya/messanger
    ports:
      - "1883:1883"
    links:
      - rabbit-server
      - redis
      - mysql
    networks:
      - webnet
  rabbit-server:
    image: "rabbitmq:3-management"
    hostname: localhost
    environment:
      #RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER : guest
      RABBITMQ_DEFAULT_PASS : guest
    ports:
      - "5672:5672"
      - "15672:15672"

    networks:
      - webnet

  redis:
    image: "redis:alpine"

  mysql:
    image: mysql
    container_name: database.dev
    command: mysqld --user=root --verbose

    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "user_messages"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

networks:
  webnet:
volumes:
  redis-data: